### ISSUE TITLE
Empty columns collapse

### ISSUE THREAD

**Issue by holic** [basscss/grid#1]
I'm working on a template that lays out a set of data in a grid. In some cases, a column may be empty. When this happens, however, the grid collapses as if the column doesn't exist in the markup.

See here:
https://jsbin.com/yaqokopiki/1/edit?html,output

This is what it looks like in Bootstrap and what I would expect to happen:
https://jsbin.com/metehebaye/1/edit?html,output

**Comment by jxnblk** [comment]
Yup. Bootstrap adds a min-height to each column which sort of goes against Basscss's principles.

For Basscss's approach, I'd suggest either:
- Using margins to push/pull columns
- Putting `&nbsp;` in any empty columns
- Putting `min-height: 1px` in an inline style where needed – hopefully not very often
- Or adding a `.no-collapse` style in your own CSS

**Comment by holic** [comment]
Got it. Thanks.
