### ISSUE TITLE
Negative margin dont work for px4

### ISSUE THREAD

**Issue by borisrorsvort** [basscss/grid#2]
I had no issues with the combinaison of px2 & mxn2 but I just tried with px4 and mxn4  and it increases the global width causing a scroll. Any idea ?
![screencast 2015-12-11 15-26-36](https://cloud.githubusercontent.com/assets/39081/11746059/4a987860-a01c-11e5-93df-68e21dc8b1cd.gif)

**Comment by jxnblk** [comment]
That's just how negative margins work. You can either add a padded container around it or set overflow hidden to compensate for the margins.

**Comment by borisrorsvort** [comment]
But if px2 only works because the container around mxn2 has equivalent px2 padding, then why event propose mxn4 since this only mainly used for that situation ?

What you mean is that I should have .container.px4 > .clearfix.mxn4 > .col.col-6.px4 + .col.col-6.px4  ?

**Comment by borisrorsvort** [comment]
Also this example shows mxn3 in the same situation and that works without overflow-hidden http://www.basscss.com/docs/grid/#gutters 
Also Im using basscss-sass.

**Comment by jxnblk** [comment]
The point of negative margin styles is that grid columns horizontally align with elements that are outside of the grid. That said the way Basscss is set up makes them completely optional.
